database:
  host: 'localhost'
  port: '5432'
  name: 'schedule_construction_service'
  schema: 'schedule_construction_service'
  user: 'schedule_construction_service'
  password: 'schedule_construction_service'

spring:
  r2dbc:
    url: 'r2dbc:postgresql://${database.host}:${database.port}/${database.name}?schema=${database.schema}'
    username: '${database.user}'
    password: '${database.password}'
  flyway:
    enabled: 'true'
    url: 'jdbc:postgresql://${database.host}:${database.port}/${database.name}'
    user: '${spring.r2dbc.username}'
    password: '${spring.r2dbc.password}'
    default-schema: '${database.schema}'

springdoc:
  webjars:
    prefix: ''

server:
  port: 11000