database:
  host: 'localhost'
  port: '5432'
  name: 'schedule_construction_service'
  schema: 'schedule_construction_service'
  user: 'schedule_construction_service'
  password: 'schedule_construction_service'

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  r2dbc:
    url: 'r2dbc:postgresql://${database.host}:${database.port}/${database.name}?schema=${database.schema}'
    username: '${database.user}'
    password: '${database.password}'
  flyway:
    enabled: 'true'
    url: 'jdbc:postgresql://${database.host}:${database.port}/${database.name}'
    user: '${spring.r2dbc.username}'
    password: '${spring.r2dbc.password}'
    default-schema: '${database.schema}'
  cache:
    jcache:
      config: 'classpath:ehcache.xml'
  sleuth:
    web:
      enabled: true

springdoc:
  webjars:
    prefix: ''

logging:
  config: classpath:logback/logback-spring.xml

messages:
  encoding: 'UTF-8'
  basename: 'classpath:messages/messages'

server:
  port: 11000