app:
  grpc:
    port: 12012
    clients:
      other-service-host: localhost:12000
  http:
    port: 11012
  database:
    port: '7003'
  kafka:
    brokers: localhost:5002

kafka:
  consuming-enabled: true